on:
  push:
  schedule:
  - cron: '33 2 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: exec .github/clean.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
