on: push

jobs:
  push:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: exec .github/push.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
